/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/tracking/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config12.geo"
#/rat/db/set DETECTOR gdml_file "annie_v04.gdml"
#/rat/db/load ANNIE/ANNIE_InnerStructure.geo
#/rat/db/load ANNIE/ANNIE_MRD_FACC.geo

/rat/db/load ANNIE/ANNIE_AmBesource.geo

/run/initialize

/process/activate Cerenkov
/glg4scint/on
#/glg4scint/reemission on

#/process/inactivate DeferTrackProc all
#/process/activate DeferTrackProc gamma
#/process/activate DeferTrackProc e+
#/process/activate DeferTrackProc e-

#initialize the visualizer
/vis/open OGLIQt 10000
/vis/scene/create

/vis/scene/add/volume
/vis/scene/add/trajectories
/vis/viewer/reset
/vis/viewer/set/style surface
/vis/drawVolume

#/vis/viewer/set/viewpointThetaPhi 20 20
/vis/viewer/set/viewpointVector 0.001 0.0005 0.1
/vis/viewer/zoom 1.5
#/vis/viewer/pan 1.0 -2.2 m  # this finally works !
/vis/viewer/pan 0.5 0.2 m  # this finally works !
/vis/viewer/set/upVector 0 1 0

#####################
# BEGIN EVENT LOOP

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid
/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

# Use IO.default_output_filename
/rat/proclast outroot

/generator/add combo gun:point
/generator/pos/set 0.1 -33.8 1749.4
/generator/vtx/set neutron 0 0 0 2.5e-8
/run/beamOn 10

/generator/vtx/set e- 0 0 1 40
/run/beamOn 1

/generator/vtx/set e- 0 0 1 30
/run/beamOn 1

/generator/vtx/set e- 0 0 1 20
/run/beamOn 1

/generator/vtx/set e- 0 0 1 10
/run/beamOn 1

/generator/vtx/set e- 0 -1 0 10
/run/beamOn 1

/generator/vtx/set e- 0 1 0 10
/run/beamOn 1

/generator/vtx/set e- -1 0 0 10
/run/beamOn 1

/generator/vtx/set e- 1 0 0 10
/run/beamOn 1

#END EVENT LOOP
#####################

/vis/viewer/refresh
/vis/viewer/flush



